import { useState, useEffect } from "react";
const T = {
  en: { title: "Dr. Osman Elrayah Omar Hassabalah", subtitle: "Internal Medicine · Telehealth · Medical Advisory · Wellness & Longevity · Aesthetic Medicine", patientBtn: "Patient Intake", historyBtn: "Session History", settingsBtn: "Settings", langBtn: "العربية", runBtn: "Run", generating: "Generating...", copyBtn: "Copy", copied: "Copied ✓", exportBtn: "Export PDF", compareBtn: "Compare Roles", inputPlaceholder: "Enter clinical details, patient info, or topic...", responseTitle: "AI Response", noHistory: "No history yet", pinTitle: "Medical Advisor Access", pinLabel: "Enter PIN", pinSubmit: "Unlock", pinWrong: "Incorrect PIN", pinLocked: "Locked. Try again in", seconds: "seconds", settingsTitle: "Settings", changePinTitle: "Change Medical Advisor PIN", currentPin: "Current PIN", newPin: "New PIN", confirmPin: "Confirm New PIN", savePin: "Save PIN", pinChanged: "PIN changed successfully", pinMismatch: "PINs do not match", pinWrongCurrent: "Current PIN is incorrect", auditLog: "PIN Change Audit Log", patientTitle: "Patient Intake Form", patientName: "Full Name", patientAge: "Age", patientGender: "Gender", patientMale: "Male", patientFemale: "Female", patientComplaint: "Chief Complaint", patientDuration: "Duration", patientSymptoms: "Key Symptoms", patientMeds: "Current Medications", patientAllergies: "Allergies", patientHistory: "Medical History", patientSubmit: "Start Consultation", patientClear: "Clear", favoritesLabel: "Favorites", allLabel: "All Commands", compareTitle: "Role Comparison", selectRoles: "Select 2 roles to compare:", runCompare: "Compare", disclaimer: "This output is AI-assisted and intended for use by qualified medical professionals only. Not a substitute for clinical judgment." },
  ar: { title: "د. عثمان الريح عمر حسب الله", subtitle: "طب باطني · تطبيب عن بُعد · استشارات طبية · الصحة والشيخوخة · الطب التجميلي", patientBtn: "استمارة المريض", historyBtn: "سجل الجلسة", settingsBtn: "الإعدادات", langBtn: "English", runBtn: "تشغيل", generating: "جارٍ التوليد...", copyBtn: "نسخ", copied: "تم النسخ ✓", exportBtn: "تصدير PDF", compareBtn: "مقارنة الأدوار", inputPlaceholder: "أدخل التفاصيل السريرية...", responseTitle: "رد الذكاء الاصطناعي", noHistory: "لا يوجد سجل بعد", pinTitle: "دخول قسم الاستشارات", pinLabel: "أدخل رمز PIN", pinSubmit: "فتح", pinWrong: "رمز PIN غير صحيح", pinLocked: "مقفل. حاول خلال", seconds: "ثانية", settingsTitle: "الإعدادات", changePinTitle: "تغيير رمز PIN", currentPin: "PIN الحالي", newPin: "PIN الجديد", confirmPin: "تأكيد PIN", savePin: "حفظ PIN", pinChanged: "تم تغيير PIN بنجاح", pinMismatch: "رمزا PIN غير متطابقين", pinWrongCurrent: "PIN الحالي غير صحيح", auditLog: "سجل تغييرات PIN", patientTitle: "استمارة بيانات المريض", patientName: "الاسم الكامل", patientAge: "العمر", patientGender: "الجنس", patientMale: "ذكر", patientFemale: "أنثى", patientComplaint: "الشكوى الرئيسية", patientDuration: "مدة الأعراض", patientSymptoms: "الأعراض", patientMeds: "الأدوية الحالية", patientAllergies: "الحساسية", patientHistory: "التاريخ المرضي", patientSubmit: "بدء الاستشارة", patientClear: "مسح", favoritesLabel: "المفضلة", allLabel: "جميع الأوامر", compareTitle: "مقارنة الأدوار", selectRoles: "اختر دورين:", runCompare: "قارن", disclaimer: "هذا المحتوى مُوَلَّد بمساعدة الذكاء الاصطناعي ومخصص للمتخصصين الطبيين فقط." }
};
const getRoles = (lang) => [
  { id: "internal", icon: "🫀", label: lang==="en"?"Internal Medicine":"طب باطني", color: "#C0392B", accent: "#E74C3C", systemPrompt: `You are an AI clinical assistant to Dr. Osman Elrayah, Internal Medicine Specialist. Follow ADA, ESC, AHA, NICE guidelines. Use SOAP format. Include evidence levels. ${lang==="ar"?"Respond in Arabic.":""}`, commands: [{ cmd: "/ddx", title: lang==="en"?"Differential Diagnosis":"التشخيص التفريقي", desc: lang==="en"?"Ranked DDx with red flags":"قائمة التشخيصات", prompt: "Generate ranked differential diagnosis with red flags for: " },{ cmd: "/workup", title: lang==="en"?"Investigation Workup":"خطة الفحوصات", desc: lang==="en"?"Evidence-based labs":"فحوصات مختبرية", prompt: "Create evidence-based investigation workup for: " },{ cmd: "/chronic", title: lang==="en"?"Chronic Disease Plan":"خطة الأمراض المزمنة", desc: lang==="en"?"Management plan":"خطة إدارة", prompt: "Create chronic disease management plan for: " },{ cmd: "/guidelines", title: lang==="en"?"Latest Guidelines":"أحدث الإرشادات", desc: lang==="en"?"Clinical guidelines":"إرشادات سريرية", prompt: "Summarize latest clinical guidelines for: " },{ cmd: "/drug", title: lang==="en"?"Drug Review":"مراجعة الدواء", desc: lang==="en"?"Interactions & dosing":"التفاعلات والجرعات", prompt: "Provide clinical drug review for: " },{ cmd: "/case", title: lang==="en"?"Case Summary":"ملخص الحالة", desc: lang==="en"?"SOAP write-up":"ملخص SOAP", prompt: "Write SOAP clinical case summary for: " }] },
  { id: "telehealth", icon: "💻", label: lang==="en"?"Telehealth":"تطبيب عن بُعد", color: "#1A6B8A", accent: "#2E86AB", systemPrompt: `You are an AI assistant for Dr. Osman Elrayah's telehealth practice. Be warm and patient-centered. Always include red flags. ${lang==="ar"?"Respond in Arabic.":""}`, commands: [{ cmd: "/consult", title: lang==="en"?"Consult Note":"ملاحظة استشارة", desc: lang==="en"?"Virtual consultation":"استشارة افتراضية", prompt: "Write telehealth SOAP consultation note for: " },{ cmd: "/followup", title: lang==="en"?"Follow-up":"متابعة", desc: lang==="en"?"Patient follow-up":"متابعة المريض", prompt: "Write follow-up message for patient with: " },{ cmd: "/triage", title: lang==="en"?"Remote Triage":"الفرز عن بُعد", desc: lang==="en"?"Urgency assessment":"تقييم الإلحاح", prompt: "Provide remote triage with urgency level for: " },{ cmd: "/edu", title: lang==="en"?"Patient Education":"تثقيف المريض", desc: lang==="en"?"Plain language":"لغة بسيطة", prompt: "Write patient education material for: " },{ cmd: "/consent", title: lang==="en"?"Consent":"الموافقة", desc: lang==="en"?"Telehealth consent":"موافقة التطبيب", prompt: "Draft telehealth informed consent for: " },{ cmd: "/recap", title: lang==="en"?"Visit Summary":"ملخص الزيارة", desc: lang==="en"?"Post-visit summary":"ملخص ما بعد الزيارة", prompt: "Write post-visit summary for: " }] },
  { id: "advisor", icon: "📋", label: lang==="en"?"Medical Advisor":"المستشار الطبي", color: "#5D4E8C", accent: "#7B68EE", protected: true, systemPrompt: `You are an AI assistant to Dr. Osman Elrayah as Pharmaceutical Physician. Follow FDA, EMA, WHO, ICH guidelines. Use regulatory-grade language. ${lang==="ar"?"Respond in Arabic.":""}`, commands: [{ cmd: "/medaffairs", title: lang==="en"?"Medical Affairs":"الشؤون الطبية", desc: lang==="en"?"Strategic brief":"ملخص استراتيجي", prompt: "Write medical affairs brief for: " },{ cmd: "/safety", title: lang==="en"?"Safety Signal":"إشارة السلامة", desc: lang==="en"?"Pharmacovigilance":"يقظة دوائية", prompt: "Conduct pharmacovigilance safety signal review for: " },{ cmd: "/dossier", title: lang==="en"?"Clinical Dossier":"الملف السريري", desc: lang==="en"?"Regulatory summary":"ملخص تنظيمي", prompt: "Draft clinical dossier section for: " },{ cmd: "/kol", title: lang==="en"?"KOL Points":"نقاط الخبراء", desc: lang==="en"?"Scientific communication":"تواصل علمي", prompt: "Develop KOL talking points for: " },{ cmd: "/protocol", title: lang==="en"?"Protocol":"بروتوكول", desc: lang==="en"?"Study protocol":"بروتوكول دراسة", prompt: "Create clinical study protocol for: " },{ cmd: "/regs", title: lang==="en"?"Regulatory":"تنظيمي", desc: lang==="en"?"Compliance review":"مراجعة امتثال", prompt: "Perform regulatory compliance review for: " }] },
  { id: "wellness", icon: "🌿", label: lang==="en"?"Wellness & Longevity":"الصحة والشيخوخة", color: "#2E7D52", accent: "#43AA8B", systemPrompt: `You are an AI wellness advisor to Dr. Osman Elrayah. Use evidence-based longevity science. Reference Attia, Sinclair, Longo. ${lang==="ar"?"Respond in Arabic.":""}`, commands: [{ cmd: "/bioage", title: lang==="en"?"Biological Age":"العمر البيولوجي", desc: lang==="en"?"Longevity plan":"خطة الشيخوخة", prompt: "Create biological age optimization protocol for: " },{ cmd: "/metabolic", title: lang==="en"?"Metabolic Reset":"إعادة ضبط الأيض", desc: lang==="en"?"Metabolic plan":"خطة أيضية", prompt: "Design metabolic reset plan for: " },{ cmd: "/longevity", title: lang==="en"?"Longevity Markers":"مؤشرات الشيخوخة", desc: lang==="en"?"Biomarkers":"مؤشرات حيوية", prompt: "Explain longevity biomarkers for: " },{ cmd: "/fasting", title: lang==="en"?"Fasting Protocol":"بروتوكول الصيام", desc: lang==="en"?"Fasting plan":"خطة صيام", prompt: "Design fasting protocol for: " },{ cmd: "/nutrx", title: lang==="en"?"Supplements":"المكملات", desc: lang==="en"?"Nutraceuticals":"مكملات غذائية", prompt: "Recommend nutraceutical protocol for: " },{ cmd: "/lifestyle", title: lang==="en"?"Lifestyle Rx":"وصفة الحياة", desc: lang==="en"?"Lifestyle plan":"خطة نمط حياة", prompt: "Write lifestyle medicine prescription for: " }] },
  { id: "aesthetic", icon: "✨", label: lang==="en"?"Aesthetic Medicine":"الطب التجميلي", color: "#8B6914", accent: "#D4A017", systemPrompt: `You are an AI assistant to Dr. Osman Elrayah integrating endocrinology and aesthetic medicine. Follow AAD guidelines. ${lang==="ar"?"Respond in Arabic.":""}`, commands: [{ cmd: "/skinrx", title: lang==="en"?"Skin Protocol":"بروتوكول الجلد", desc: lang==="en"?"Skin health":"صحة الجلد", prompt: "Create skin health protocol for: " },{ cmd: "/collagen", title: lang==="en"?"Anti-Aging":"مضاد الشيخوخة", desc: lang==="en"?"Collagen plan":"خطة الكولاجين", prompt: "Design anti-aging collagen plan for: " },{ cmd: "/bodyscan", title: lang==="en"?"Body Composition":"تركيبة الجسم", desc: lang==="en"?"Body plan":"خطة الجسم", prompt: "Create body composition plan for: " },{ cmd: "/hormones", title: lang==="en"?"Hormones":"الهرمونات", desc: lang==="en"?"Hormonal balance":"توازن هرموني", prompt: "Design hormonal balance protocol for: " },{ cmd: "/pcos", title: lang==="en"?"PCOS":"تكيس المبايض", desc: lang==="en"?"PCOS protocol":"بروتوكول PCOS", prompt: "Create PCOS management plan for: " },{ cmd: "/thyroid", title: lang==="en"?"Thyroid":"الغدة الدرقية", desc: lang==="en"?"Thyroid plan":"خطة الغدة", prompt: "Design thyroid optimization plan for: " }] },
  { id: "outreach", icon: "📣", label: lang==="en"?"Patient Outreach":"التواصل", color: "#B5451B", accent: "#E8671C", systemPrompt: `You are a medical content strategist for Dr. Osman Elrayah. Voice: authoritative yet accessible. Medically accurate. ${lang==="ar"?"Respond in Arabic.":""}`, commands: [{ cmd: "/post", title: lang==="en"?"Social Post":"منشور", desc: lang==="en"?"LinkedIn/Instagram":"لينكدإن/إنستغرام", prompt: "Write engaging medical social media post about: " },{ cmd: "/thread", title: lang==="en"?"Thread":"خيط", desc: lang==="en"?"Twitter thread":"خيط تويتر", prompt: "Write 8-tweet educational thread about: " },{ cmd: "/newsletter", title: lang==="en"?"Newsletter":"نشرة", desc: lang==="en"?"Patient newsletter":"نشرة للمرضى", prompt: "Write health newsletter section about: " },{ cmd: "/bio", title: lang==="en"?"Professional Bio":"السيرة", desc: lang==="en"?"Doctor profile":"ملف الطبيب", prompt: "Write professional bio for Dr. Osman highlighting: " },{ cmd: "/faq", title: lang==="en"?"Patient FAQ":"أسئلة شائعة", desc: lang==="en"?"Common questions":"أسئلة المرضى", prompt: "Write patient FAQ about: " },{ cmd: "/whatsapp", title: lang==="en"?"WhatsApp Reply":"رد واتساب", desc: lang==="en"?"Patient message":"رسالة مريض", prompt: "Write WhatsApp reply to patient asking about: " }] }
];
export default function App() {
  const [lang,setLang]=useState("en");
  const [activeRole,setActiveRole]=useState("internal");
  const [selectedCmd,setSelectedCmd]=useState(null);
  const [userInput,setUserInput]=useState("");
  const [aiResponse,setAiResponse]=useState("");
  const [loading,setLoading]=useState(false);
  const [copied,setCopied]=useState(false);
  const [favorites,setFavorites]=useState([]);
  const [history,setHistory]=useState([]);
  const [showHistory,setShowHistory]=useState(false);
  const [showPatient,setShowPatient]=useState(false);
  const [showSettings,setShowSettings]=useState(false);
  const [showPin,setShowPin]=useState(false);
  const [pinInput,setPinInput]=useState("");
  const [pinError,setPinError]=useState("");
  const [pinLocked,setPinLocked]=useState(false);
  const [pinLockSeconds,setPinLockSeconds]=useState(0);
  const [pinAttempts,setPinAttempts]=useState(0);
  const [advisorUnlocked,setAdvisorUnlocked]=useState(false);
  const [currentPin,setCurrentPin]=useState("241969");
  const [auditLog,setAuditLog]=useState([]);
  const [pinChangeForm,setPinChangeForm]=useState({current:"",new:"",confirm:""});
  const [pinChangeMsg,setPinChangeMsg]=useState("");
  const [patientData,setPatientData]=useState({name:"",age:"",gender:"",complaint:"",duration:"",symptoms:"",meds:"",allergies:"",history:""});
  const t=T[lang]; const roles=getRoles(lang); const role=roles.find(r=>r.id===activeRole); const isRtl=lang==="ar";
  useEffect(()=>{if(pinLockSeconds>0){const timer=setTimeout(()=>setPinLockSeconds(s=>s-1),1000);return()=>clearTimeout(timer);}else if(pinLockSeconds===0&&pinLocked){setPinLocked(false);setPinAttempts(0);}},[pinLockSeconds,pinLocked]);
  const handleRoleSelect=(roleId)=>{const r=roles.find(x=>x.id===roleId);if(r?.protected&&!advisorUnlocked){setShowPin(true);return;}setActiveRole(roleId);setSelectedCmd(null);setAiResponse("");};
  const handlePinSubmit=()=>{if(pinLocked)return;if(pinInput===currentPin){setAdvisorUnlocked(true);setActiveRole("advisor");setSelectedCmd(null);setAiResponse("");setShowPin(false);setPinInput("");setPinError("");setPinAttempts(0);}else{const a=pinAttempts+1;setPinAttempts(a);setPinError(t.pinWrong);setPinInput("");if(a>=5){setPinLocked(true);setPinLockSeconds(60);setShowPin(false);}}};
  const handlePinChange=()=>{if(pinChangeForm.current!==currentPin){setPinChangeMsg(t.pinWrongCurrent);return;}if(pinChangeForm.new!==pinChangeForm.confirm){setPinChangeMsg(t.pinMismatch);return;}const old=currentPin;setCurrentPin(pinChangeForm.new);setAuditLog(prev=>[...prev,{time:new Date().toLocaleString(),old:old.replace(/./g,"•"),updated:pinChangeForm.new.replace(/./g,"•")}]);setPinChangeForm({current:"",new:"",confirm:""});setPinChangeMsg(t.pinChanged);setAdvisorUnlocked(false);};
  const handleRun=async()=>{if(!userInput.trim()||!selectedCmd)return;setLoading(true);setAiResponse("");try{let prompt=selectedCmd.prompt+userInput;if(patientData.name)prompt=`Patient: ${patientData.name}, Age: ${patientData.age}, Gender: ${patientData.gender}\nComplaint: ${patientData.complaint}\nSymptoms: ${patientData.symptoms}\nMeds: ${patientData.meds}\n\n${prompt}`;const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:1000,system:role.systemPrompt,messages:[{role:"user",content:prompt}]})});const data=await res.json();const text=data.content?.map(b=>b.text||"").join("\n")||"No response.";setAiResponse(text);setHistory(prev=>[{id:Date.now(),cmd:selectedCmd.cmd,title:selectedCmd.title,role:role.label,response:text,time:new Date().toLocaleTimeString()},...prev]);}catch(e){setAiResponse("Error: "+e.message);}setLoading(false);};
  const handleCopy=()=>{navigator.clipboard.writeText(aiResponse);setCopied(true);setTimeout(()=>setCopied(false),2000);};
  const exportPDF=()=>{const c=`DR. OSMAN ELRAYAH OMAR HASSABALAH\nInternal Medicine Specialist | Telehealth Consultant\n${new Date().toLocaleString()}\n${"─".repeat(50)}\nCOMMAND: ${selectedCmd?.cmd} — ${selectedCmd?.title}\n\nINPUT:\n${userInput}\n\n${"─".repeat(50)}\nRESPONSE:\n${aiResponse}\n\n${"─".repeat(50)}\nDISCLAIMER: ${t.disclaimer}`;const b=new Blob([c],{type:"text/plain"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=`DrOsman_${selectedCmd?.cmd}_${Date.now()}.txt`;a.click();URL.revokeObjectURL(u);};
  const toggleFav=(k)=>setFavorites(p=>p.includes(k)?p.filter(f=>f!==k):[...p,k]);
  const favCmds=role?role.commands.filter(c=>favorites.includes(`${activeRole}-${c.cmd}`)):[];
  const ms={app:{fontFamily:isRtl?"'Noto Naskh Arabic',serif":"'DM Sans',sans-serif",background:"linear-gradient(135deg,#0a0e1a,#111827,#0d1117)",minHeight:"100vh",color:"#e8e0d0",direction:isRtl?"rtl":"ltr"},hdr:{background:"linear-gradient(90deg,#1a1f2e,#232840)",borderBottom:"1px solid rgba(212,160,23,0.25)",padding:"14px 20px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap"},av:{width:44,height:44,borderRadius:"50%",background:"linear-gradient(135deg,#D4A017,#8B6914)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,fontWeight:700,color:"#fff",flexShrink:0},btn:(c)=>({background:c||"#1e2433",border:`1px solid ${c?"transparent":"#2a3040"}`,color:c?"#000":"#8892a4",padding:"6px 12px",borderRadius:6,cursor:"pointer",fontSize:12}),modal:{position:"fixed",inset:0,background:"rgba(0,0,0,0.75)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000,padding:16},mbox:{background:"#161b29",border:"1px solid #2a3040",borderRadius:14,padding:24,width:"100%",maxWidth:480,maxHeight:"85vh",overflowY:"auto"},inp:{width:"100%",boxSizing:"border-box",background:"#0d1117",border:"1px solid #2a3040",borderRadius:8,color:"#e8e0d0",padding:"9px 12px",fontSize:13,fontFamily:"inherit",outline:"none",marginBottom:10}};
  return (
    <div style={ms.app}>
      <div style={ms.hdr}>
        <div style={{display:"flex",alignItems:"center",gap:12}}>
          <div style={ms.av}>OE</div>
          <div>
            <div style={{fontSize:15,fontWeight:700,color:"#D4A017"}}>{t.title}</div>
            <div style={{fontSize:11,color:"#6b7280"}}>{t.subtitle}</div>
          </div>
        </div>
        <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>
          <button style={ms.btn()} onClick={()=>setShowPatient(true)}>📋 {t.patientBtn}</button>
          <button style={ms.btn()} onClick={()=>setShowHistory(true)}>🕐 {t.historyBtn}</button>
          <button style={ms.btn()} onClick={()=>setShowSettings(true)}>⚙️ {t.settingsBtn}</button>
          <button style={{...ms.btn(),color:"#D4A017",borderColor:"#D4A01744"}} onClick={()=>setLang(l=>l==="en"?"ar":"en")}>🌐 {t.langBtn}</button>
        </div>
      </div>
      <div style={{display:"flex",overflowX:"auto",background:"#0d1117",borderBottom:"1px solid #1e2433",padding:"0 8px"}}>
        {roles.map(r=>(
          <button key={r.id} onClick={()=>handleRoleSelect(r.id)} style={{background:activeRole===r.id?`${r.color}18`:"transparent",border:"none",borderBottom:activeRole===r.id?`2px solid ${r.accent}`:"2px solid transparent",color:activeRole===r.id?r.accent:"#6b7280",padding:"10px 12px",cursor:"pointer",fontSize:12,fontWeight:activeRole===r.id?700:400,whiteSpace:"nowrap"}}>
            {r.icon} {r.label} {r.protected&&!advisorUnlocked?"🔒":""}
          </button>
        ))}
      </div>
      <div style={{padding:16,maxWidth:960,margin:"0 auto"}}>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))",gap:10,marginBottom:16}}>
          {role?.commands.map(cmd=>{
            const k=`${activeRole}-${cmd.cmd}`;const sel=selectedCmd?.cmd===cmd.cmd;
            return (
              <div key={cmd.cmd} onClick={()=>{setSelectedCmd(cmd);setAiResponse("");setUserInput("");}} style={{background:sel?`${role.color}28`:"#161b29",border:`1.5px solid ${sel?role.accent:"#1e2433"}`,borderRadius:10,padding:"12px 14px",cursor:"pointer",position:"relative"}}>
                <button onClick={e=>{e.stopPropagation();toggleFav(k);}} style={{position:"absolute",top:10,right:10,background:"none",border:"none",cursor:"pointer",fontSize:14,color:favorites.includes(k)?"#D4A017":"#3a4050"}}>{favorites.includes(k)?"★":"☆"}</button>
                <span style={{backgroun
